update-ce: add parameter 'nightly' to update with latest nightly build

diff --git a/projects/Amlogic-ce/filesystem/usr/sbin/update-ce b/projects/Amlogic-ce/filesystem/usr/sbin/update-ce
--- a/projects/Amlogic-ce/filesystem/usr/sbin/update-ce
+++ b/projects/Amlogic-ce/filesystem/usr/sbin/update-ce
@@ -69,6 +69,24 @@ case "${url}" in
         ;;
     esac
     ;;
+  nightly)
+    source /etc/os-release
+
+    latest_tar=$(curl -s "https://relkai.coreelec.org/?dir=${DISTRO_DEVICE}/ce-${VERSION_ID%.*}" |
+      grep -oE "CoreELEC-${DISTRO_ARCH}-${VERSION_ID}-[a-zA-Z]+_nightly_[0-9]{8}\.tar" | head -n1)
+
+    if [ -n "${latest_tar}" ]; then
+      echo "latest update: ${latest_tar}"
+      echo
+
+      curl -f -L -O "https://relkai.coreelec.org/${DISTRO_DEVICE}/ce-${VERSION_ID%.*}/${latest_tar}"
+      [ $? -eq 0 ] && do_reboot || show_error
+    else
+      echo "Can't get link for latest nightly build"
+      show_error
+    fi
+
+    ;;
   *)
     if [ -n "${file}" ]; then
       if [ -f "${file}" ]; then
@@ -97,7 +115,9 @@ case "${url}" in
     echo "update-ce: missing url"
     echo
     echo "Usage: update-ce <url> [nocompat]"
-    echo "  <url> mega/http/ftp url or local file .tar or .img.gz"
+    echo "  <url>: mega/http/ftp link"
+    echo "  <url>: local file .tar or .img.gz"
+    echo "  <url>: nightly - updates with latest nightly build"
     echo "  [nocompat] disable compatibility checks and risk a non-booting system"
     echo
     exit 1
